### PR TITLE
move scripts to their right place to clean up the root directory

### PR DESCRIPTION
**Pull request by hjk41**
our root directory is too messy...

### CODE REVIEW

**Comment by jermainewang** [comment]
Have you done an end-to-end test from downloading to compiling? If it works, I think you could just merge it. The change is fine to me.

**Comment by jermainewang** [comment]
BTW, I think put `setup.py` in the root directory is better (personal taste).

**Comment by hjk41** [comment]
The download-xxx.sh scripts are standalone scripts, they are for single
packages that just downloads one thing. I think we should just have one
shell for all the dependencies and let user choose which packages they want
to install. I prefer to put setup.py in the Python directory just because I
don't like too many files in the root directory.

On Tue, Apr 21, 2015 at 11:25 PM, Minjie Wang <notifications@github.com>
wrote:

> BTW, I think put setup.py in the root directory is better (personal
> taste).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/minerva/pull/22#issuecomment-94838224>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hotpxl** [comment]
Don't worry about the dependencies. I'll remove boost soon and we can ship with glog and gflags.

**Comment by jermainewang** [comment]
Ok, I am with your suggestion. I think we could wait for @hotpxl 's changing on cython.

**Comment by hjk41** [comment]
sure. Yutian, could you merge the change after you have finished with
Cython?

On Wed, Apr 22, 2015 at 10:46 AM, Minjie Wang <notifications@github.com>
wrote:

> Ok, I am with your suggestion. I think we could wait for @hotpxl
> <https://github.com/hotpxl> 's changing on cython.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/minerva/pull/22#issuecomment-95006330>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hotpxl** [comment]
I think we could merge this first. Cython is not thoroughly tested yet. @jermainewang is reviewing my code, but I don't have time yet to discuss with him. Sorry about the delay.

**Comment by jermainewang** [comment]
Close this since we are now working on this in `athena-cython` branch.

**Pull request closed without merging**
